In [29]:
import pandas as pd

df = pd.read_csv('estoque_produtos_100_itens.csv',
                sep=";"
            )

print()
print("df.head(3)")
print(df.head(3))

df.head(3)
   Codigo  Estoque  Preco  Vencimento                 Descricao
0    1000      414  15.72  2028-03-15          Leite Vida Light
1    1001      959  37.65  2026-10-31  Queijo Saboroso Especial
2    1002      647  39.81  2027-05-25       Suco Qualidade Zero

In [30]:
# Filtrando pela string, se contem ou não um item
df_produtos_gourmet = df[(df['Descricao'].str.contains('A'))]

display(df_produtos_gourmet)

# termina com uma string
df_produtos_gourmet = df[(df['Descricao'].str.endswith('Especial'))]

display(df_produtos_gourmet)

# começa com uma string
df_produtos_gourmet = df[(df['Descricao'].str.startswith('Achocolatado '))]

display(df_produtos_gourmet)

    Codigo  Estoque  Preco  Vencimento                          Descricao
5     1005      772  89.21  2026-07-24                 Arroz Top Especial
46    1046      789  43.15  2027-07-31            Achocolatado Extra Zero
50    1050      278  39.95  2027-05-20      Achocolatado Saboroso Caseiro
52    1052      252  83.22  2027-11-10  Achocolatado Saboroso Tradicional
73    1073      520  31.54  2027-07-03             Arroz Saboroso Caseiro
74    1074      729  70.24  2028-05-02               Açúcar Vida Integral
80    1080      681  60.79  2028-04-27          Achocolatado Premium Zero
90    1090      465  26.91  2026-05-31            Açúcar Fazenda Refinado

    Codigo  Estoque  Preco  Vencimento                         Descricao
1     1001      959  37.65  2026-10-31          Queijo Saboroso Especial
3     1003       53  87.23  2027-09-29            Sal Qualidade Especial
4     1004      478  66.29  2027-04-09             Óleo Premium Especial
5     1005      772  89.21  2026-07-24                Arroz Top Especial
6     1006      945  39.84  2026-06-10                 Suco Top Especial
14    1014      840  76.71  2028-03-21   Creme Dental Qualidade Especial
15    1015      325  18.26  2026-09-27        Creme Dental Vida Especial
21    1021      955  21.92  2026-07-01       Detergente Premium Especial
29    1029      820  17.84  2026-12-07           Maionese Extra Especial
31    1031      372  72.72  2027-01-18         Presunto Premium Especial
53    1053      563  51.93  2026-07-09          Vinagre Fazenda Especial
55    1055      784  67.96  2027-02-12            Suco Saboroso Especial
61    1061      245  34.63  2026-08-12              Queijo Vida Especial
62    1062      158  29.55  2028-01-01                 Pão Vida Especial
64    1064      430   7.38  2028-01-14           Biscoito Extra Especial
65    1065      776  66.89  2028-04-16              Leite Extra Especial
78    1078      999  40.96  2026-06-11            Farinha Extra Especial
85    1085      425  76.14  2026-09-16          Iogurte Premium Especial
88    1088      762  63.16  2027-10-04  Molho de Tomate Fazenda Especial
95    1095      910  73.10  2028-02-02        Farinha Qualidade Especial

    Codigo  Estoque  Preco  Vencimento                          Descricao
46    1046      789  43.15  2027-07-31            Achocolatado Extra Zero
50    1050      278  39.95  2027-05-20      Achocolatado Saboroso Caseiro
52    1052      252  83.22  2027-11-10  Achocolatado Saboroso Tradicional
80    1080      681  60.79  2028-04-27          Achocolatado Premium Zero

In [31]:
# regex de pesquisa de multiplos itens
filtro = r"Especial|Gourmet"

df_produtos_gourmet = df[(df['Descricao'].str.contains(filtro))]

display(df_produtos_gourmet)
display(df_produtos_gourmet['Preco'].mean())

     Codigo  Estoque  Preco  Vencimento                         Descricao
1      1001      959  37.65  2026-10-31          Queijo Saboroso Especial
3      1003       53  87.23  2027-09-29            Sal Qualidade Especial
4      1004      478  66.29  2027-04-09             Óleo Premium Especial
5      1005      772  89.21  2026-07-24                Arroz Top Especial
6      1006      945  39.84  2026-06-10                 Suco Top Especial
14     1014      840  76.71  2028-03-21   Creme Dental Qualidade Especial
15     1015      325  18.26  2026-09-27        Creme Dental Vida Especial
21     1021      955  21.92  2026-07-01       Detergente Premium Especial
29     1029      820  17.84  2026-12-07           Maionese Extra Especial
31     1031      372  72.72  2027-01-18         Presunto Premium Especial
53     1053      563  51.93  2026-07-09          Vinagre Fazenda Especial
55     1055      784  67.96  2027-02-12            Suco Saboroso Especial
61     1061      245  34.63  2026-08-12              Queijo Vida Especial
62     1062      158  29.55  2028-01-01                 Pão Vida Especial
64     1064      430   7.38  2028-01-14           Biscoito Extra Especial
65     1065      776  66.89  2028-04-16              Leite Extra Especial
78     1078      999  40.96  2026-06-11            Farinha Extra Especial
85     1085      425  76.14  2026-09-16          Iogurte Premium Especial
88     1088      762  63.16  2027-10-04  Molho de Tomate Fazenda Especial
95     1095      910  73.10  2028-02-02        Farinha Qualidade Especial
100    1099      102  60.84  2026-08-29                      Cafe Gourmet

np.float64(52.39095238095237)

In [32]:
# Criando um DataFrame de exemplo
dados = {
    'Nome': 'Carlos Ana Bruno Diego Helena'.split(),
    'Email': ['carlos@gmail.com', 'ana@outlook.com', 'bruno@yahoo.com', 'diego@gmail.com', 'helena@empresa.com.br']
}
df = pd.DataFrame(dados)

# Regex para buscar 'gmail' OU 'yahoo'
padrao = r'(gmail|yahoo)'

# Filtrando o DataFrame
resultado = df[df['Email'].str.contains(padrao, case=False, na=False)]
print(resultado)

     Nome             Email
0  Carlos  carlos@gmail.com
2   Bruno   bruno@yahoo.com
3   Diego   diego@gmail.com

C:\Users\andre\AppData\Local\Temp\ipykernel_27992\3910622326.py:12: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  resultado = df[df['Email'].str.contains(padrao, case=False, na=False)]

In [33]:
# Regex com dois grupos de captura: (usuario) @ (dominio)
padrao_extrair = r'(?P<Usuario>[\w\.-]+)@(?P<Dominio>[\w\.-]+)'

# Dá pra fazer mas não é usual
# O mais comum é mapear de um dataframe para outro
# Não é comum usar regex para fazer dataframes

# Extraindo para novas colunas
df_extraido = df['Email'].str.extract(padrao_extrair)
print(df_extraido)

  Usuario         Dominio
0  carlos       gmail.com
1     ana     outlook.com
2   bruno       yahoo.com
3   diego       gmail.com
4  helena  empresa.com.br

In [34]:
df_produtos = pd.DataFrame({'Preço': ['R$ 1.500,00', 'R$ 350,50', 'R$ 89,90']})

# Queremos buscar tudo o que NÃO for número e ponto/vírgula para remover
# \D no regex significa "tudo que não é dígito"

# Substitui tudo que não é digito por nada
# O dataframe aplica operações do str em todos os itens da coluna Preço
# todos os itens irão executar o replace(item_a_ser_substituido, item_a_substituir, regex=True ou False)

#Estamos salvando os valores atualizado da coluna Preço na coluna Preço_Limpo
df_produtos['Preço_Limpo'] = df_produtos['Preço'].str.replace(r'[^\d,]', '', regex=True)
display(df_produtos)

         Preço Preço_Limpo
0  R$ 1.500,00     1500,00
1    R$ 350,50      350,50
2     R$ 89,90       89,90

In [35]:
media_preco

NameError: name 'media_preco' is not defined